name: download videos

on:
  push:
    branches:
      - master

jobs:
  build_docs_and_deploy:
    runs-on: ubuntu-latest
    name: download

    steps:
    - name: Checkout
      uses: actions/checkout@master
    
    - name: Install You-get
      id: videos
      run: |
        cd ..
        mkdir you_get
        ls 
        echo "=========================="
        pip3 install you-get
        export PATH="$PATH:/home/runner/.local/bin:/home/runner/you_get"
        you-get -o ./you_get/ -O 11 --debug 'https://www.bilibili.com/video/BV1qa4y1Y7CD?p=11'
        you-get -o ./you_get/ -O 12 --debug 'https://www.bilibili.com/video/BV1qa4y1Y7CD?p=12'
        you-get -o ./you_get/ -O 13 --debug 'https://www.bilibili.com/video/BV1qa4y1Y7CD?p=13'
        you-get -o ./you_get/ -O 14 --debug 'https://www.bilibili.com/video/BV1qa4y1Y7CD?p=14'
        you-get -o ./you_get/ -O 15 --debug 'https://www.bilibili.com/video/BV1qa4y1Y7CD?p=15'
        you-get -o ./you_get/ -O 16 --debug 'https://www.bilibili.com/video/BV1qa4y1Y7CD?p=16'
        you-get -o ./you_get/ -O 17 --debug 'https://www.bilibili.com/video/BV1qa4y1Y7CD?p=17'
        you-get -o ./you_get/ -O 18 --debug 'https://www.bilibili.com/video/BV1qa4y1Y7CD?p=18'
        you-get -o ./you_get/ -O 19 --debug 'https://www.bilibili.com/video/BV1qa4y1Y7CD?p=19'
        you-get -o ./you_get/ -O 20 --debug 'https://www.bilibili.com/video/BV1qa4y1Y7CD?p=20'
        
        
        ls
        echo '============================================='
        cd you_get
        ls
        echo '=========================================='
        
        cd ../
        
        #mkdir c9-python-getting-started/source
        #mkdir c9-python-getting-started/source/assets
        #mkdir c9-python-getting-started/source/assets/videos
        #mkdir c9-python-getting-started/source/assets/videos/EvenmoPython
        
        cp -r you_get/. c9-python-getting-started/source/assets/videos/EvenmoPython
        cd c9-python-getting-started/
        git config --global user.email "ucecwme@ucl.ac.uk"
        git config --global user.name "nickcafferry"
        git init
        cd source/assets/videos/EvenmoPython
        git add -A
        git status 
        cd ../../../../
        git commit -m "Add some videos"
        ls
        git push origin master
