name: download videos

on:
  push:
    branches:
      - master

jobs:
  build_docs_and_deploy:
    runs-on: ubuntu-latest
    name: download

    steps:
    - name: Checkout
      uses: actions/checkout@master
    
    - name: Install You-get
      id: videos
      run: |
        cd ..
        mkdir you_get
        ls 
        echo "=========================="
        pip3 install you-get
        export PATH="$PATH:/home/runner/.local/bin:/home/runner/you_get"
        you-get -o ./you_get/ -O 1 --debug 'https://www.bilibili.com/video/BV1qa4y1Y7CD?p=1'
        you-get -o ./you_get/ -O 2 --debug 'https://www.bilibili.com/video/BV1qa4y1Y7CD?p=2'
        you-get -o ./you_get/ -O 3 --debug 'https://www.bilibili.com/video/BV1qa4y1Y7CD?p=3'
        you-get -o ./you_get/ -O 4 --debug 'https://www.bilibili.com/video/BV1qa4y1Y7CD?p=4'
        you-get -o ./you_get/ -O 5 --debug 'https://www.bilibili.com/video/BV1qa4y1Y7CD?p=5'
        you-get -o ./you_get/ -O 6 --debug 'https://www.bilibili.com/video/BV1qa4y1Y7CD?p=6'
        you-get -o ./you_get/ -O 7 --debug 'https://www.bilibili.com/video/BV1qa4y1Y7CD?p=7'
        you-get -o ./you_get/ -O 8 --debug 'https://www.bilibili.com/video/BV1qa4y1Y7CD?p=8'
        you-get -o ./you_get/ -O 9 --debug 'https://www.bilibili.com/video/BV1qa4y1Y7CD?p=9'
        you-get -o ./you_get/ -O 10 --debug 'https://www.bilibili.com/video/BV1qa4y1Y7CD?p=10'
        
        
        ls
        echo '============================================='
        cd you_get
        ls
        echo '=========================================='
        
        cd ../
        
        mkdir c9-python-getting-started/source
        mkdir c9-python-getting-started/source/assets
        mkdir c9-python-getting-started/source/assets/videos
        mkdir c9-python-getting-started/source/assets/videos/EvenmoPython
        
        cp -r you_get/. c9-python-getting-started/source/assets/videos/EvenmoPython
        cd c9-python-getting-started/
        git config --global user.email "ucecwme@ucl.ac.uk"
        git config --global user.name "nickcafferry"
        git init
        cd source/assets/videos/EvenmoPython
        git add -A
        git status 
        cd ../../../../
        git commit -m "Add some videos"
        ls
        git push origin master
