name: download videos

on:
  push:
    branches:
      - master

jobs:
  build_docs_and_deploy:
    runs-on: ubuntu-latest
    name: download

    steps:
    - name: Checkout
      uses: actions/checkout@master
    
    - name: Install You-get
      id: videos
      run: |
        cd ..
        mkdir you_get
        ls 
        echo "=========================="
        pip3 install you-get
        export PATH="$PATH:/home/runner/.local/bin:/home/runner/you_get"
        you-get -o ./you_get/ -O 21 --debug 'https://www.bilibili.com/video/BV1qa4y1Y7CD?p=21'
        you-get -o ./you_get/ -O 22 --debug 'https://www.bilibili.com/video/BV1qa4y1Y7CD?p=22'
        you-get -o ./you_get/ -O 23 --debug 'https://www.bilibili.com/video/BV1qa4y1Y7CD?p=23'
        you-get -o ./you_get/ -O 24 --debug 'https://www.bilibili.com/video/BV1qa4y1Y7CD?p=24'
        you-get -o ./you_get/ -O 25 --debug 'https://www.bilibili.com/video/BV1qa4y1Y7CD?p=25'
        you-get -o ./you_get/ -O 26 --debug 'https://www.bilibili.com/video/BV1qa4y1Y7CD?p=26'
        you-get -o ./you_get/ -O 27 --debug 'https://www.bilibili.com/video/BV1qa4y1Y7CD?p=27'
        you-get -o ./you_get/ -O 28 --debug 'https://www.bilibili.com/video/BV1qa4y1Y7CD?p=28'
        you-get -o ./you_get/ -O 29 --debug 'https://www.bilibili.com/video/BV1qa4y1Y7CD?p=29'
        you-get -o ./you_get/ -O 30 --debug 'https://www.bilibili.com/video/BV1qa4y1Y7CD?p=30'
        
        you-get -o ./you_get/ -O 31 --debug 'https://www.bilibili.com/video/BV1qa4y1Y7CD?p=31'
        
        
        ls
        echo '============================================='
        cd you_get
        ls
        echo '=========================================='
        
        cd ../
        
        #mkdir c9-python-getting-started/source
        #mkdir c9-python-getting-started/source/assets
        #mkdir c9-python-getting-started/source/assets/videos
        #mkdir c9-python-getting-started/source/assets/videos/EvenmoPython
        
        cp -r you_get/. c9-python-getting-started/source/assets/videos/EvenmoPython
        cd c9-python-getting-started/
        git config --global user.email "ucecwme@ucl.ac.uk"
        git config --global user.name "nickcafferry"
        git init
        cd source/assets/videos/EvenmoPython
        git add -A
        git status 
        cd ../../../../
        git commit -m "Add some videos"
        ls
        git push origin master
